apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  namespace: argocd
  labels:
    appName: {{ .Values.appName }}
    projectName: {{ .Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      appName: {{ .Values.appName }}
      projectName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        appName: {{ .Values.appName }}
        projectName: {{ .Chart.Name }}
    spec:
#      when initContainers enabled is true
      {{- if .Values.initContainers.enabled }}
      volumes:
        - name: vault-secret
          emptyDir: {}
      initContainers:
        - name: get-secrets
          image: public.ecr.aws/u4j6q5s8/kubernetes-vault-init-container:1.0
          env:
            - name: VAULT_ADDR
              value: https://vault-internal.pdevops78.online:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
            - name: SECRET_NAME
              value: {{ .Chart.Name }}-dev/{{ .Values.component }}
            - name: VAULT_SKIP_VERIFY
              value: "TRUE"
          volumeMounts:
            - name: vault-secret
              mountPath: /data

      {{- end }}

      containers:
        - name: {{ .Values.component }}
          image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/{{ .Chart.Name }}-{{ .Values.component }}:1.7
          {{- if .Values.initContainers.enabled }}
          volumeMounts:
            - name: vault-secret
              mountPath: /data
          {{- end }}
