apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}
  namespace: argocd
  labels:
    appName: {{ .Values.appName }}
    projectName: {{ .Chart.Name }}
spec:
  template:
    spec:
      {{ - if .Values.schemaContainers.enabled }}
      volumes:
        - name: vault-secret
          emptyDir: { }
      initContainers:
        - name: get-secrets
          image: public.ecr.aws/u4j6q5s8/kubernetes-vault-init-container:1.2
          env:
            - name: VAULT_ADDR
              value: https://vault-internal.pdevops78.online:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
            - name: SECRET_NAME
              value: {{ .Chart.Name }}-dev/{{ .Values.component }}
            - name: VAULT_SKIP_VERIFY
              value: "TRUE"
          volumeMounts:
            - name: vault-secret
              mountPath: /data

      containers:
        - name: schema
          image: public.ecr.aws/u4j6q5s8/backend-schema:1.4
          env:
            - name: db_type
              value: {{ .Values.schemaContainers.db_type }}

      restartPolicy: Never
  backoffLimit: 1
  {{- end }}
