{{ - if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
  namespace: argocd
spec:
  selector:
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  {{ - end }}

# by default service is enabled
# for dispatch component service is not necessary
#  ExpenseApp123----DB_PASS
#expense----DB_USER
