# this initContainers is for vault init container to get secrets form vault
initContainers:
  enabled: true

# this is for to load schema in job.yaml
schema:
  enabled: true
  db_type: mongodb

component: catalogue
appVersion: 2.0
appName: catalogue

# the below values pass to the service
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# this is the ingress values to attach the service to ingress to route the traffic
# here no need to route the traffic (ingress.yaml)

ingress:
  enabled: false


