initContainers:
  enabled: true
schema:
  enabled: true
  db_type: mongodb
component: catalogue
project_name: roboshop
appVersion: 1.3
appName: catalogue

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  host: catalogue-dev.pdevops78.online

