initContainers:
  enabled: true
schema:
  enabled: true
  db_type: mongodb
component: catalogue
appVersion: 1.2
appName: catalogue

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true

