schemaContainers:
  enabled: false
initContainers:
  enabled: false
component: frontend
appVersion: 1.0
appName: frontend

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true

