initContainers:
  enabled: true

schema:
  enabled: true
  db_type: mysql
  schemaVersion: 1.1

component: shipping
appVersion: 1.5
appName: shipping

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

  ingress:
    enabled: false
