initContainers:
  enabled: true

schema:
  enabled: true
  db_type: mysql

component: shipping
appVersion: 2.1
appName: shipping

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

  ingress:
    enabled: false
