initContainers:
  enabled: true

schema:
  enabled: true
  db_type: mongodb

component: user
project_name: roboshop
appVersion: 1.7
appName: user

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
